import './globals.css'
import type { Metadata } from 'next'
import { headers } from 'next/headers'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

import { cookieToInitialState } from 'wagmi'

import { config } from '@/config'
import Web3ModalProvider from '@/context'

export const metadata: Metadata = {
  title: 'ThxBro🫡',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Web3ModalProvider initialState={initialState}>{children}</Web3ModalProvider>
        <Footer />
      </body>
    </html>
  )
}